package com.daisyit.entity;
// Generated Mar 4, 2018 1:44:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Appvar generated by hbm2java
 */
@Entity
@Table(name="APPVAR"
    ,catalog="NSRP_CATER"
)
public class Appvar  implements java.io.Serializable {


     private String name;
     private char type;
     private String value;
     private String descript;
     private String inputmask;
     private byte modify;
     private String invalid;
     private char depCode;
     private int rsrId;

    public Appvar() {
    }

    public Appvar(String name, char type, String value, String descript, String inputmask, byte modify, String invalid, char depCode, int rsrId) {
       this.name = name;
       this.type = type;
       this.value = value;
       this.descript = descript;
       this.inputmask = inputmask;
       this.modify = modify;
       this.invalid = invalid;
       this.depCode = depCode;
       this.rsrId = rsrId;
    }
   
     @Id 

    
    @Column(name="NAME", unique=true, nullable=false, length=15)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="TYPE", nullable=false, length=1)
    public char getType() {
        return this.type;
    }
    
    public void setType(char type) {
        this.type = type;
    }

    
    @Column(name="VALUE", nullable=false, length=120)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="DESCRIPT", nullable=false, length=120)
    public String getDescript() {
        return this.descript;
    }
    
    public void setDescript(String descript) {
        this.descript = descript;
    }

    
    @Column(name="INPUTMASK", nullable=false, length=12)
    public String getInputmask() {
        return this.inputmask;
    }
    
    public void setInputmask(String inputmask) {
        this.inputmask = inputmask;
    }

    
    @Column(name="MODIFY", nullable=false)
    public byte getModify() {
        return this.modify;
    }
    
    public void setModify(byte modify) {
        this.modify = modify;
    }

    
    @Column(name="INVALID", nullable=false, length=12)
    public String getInvalid() {
        return this.invalid;
    }
    
    public void setInvalid(String invalid) {
        this.invalid = invalid;
    }

    
    @Column(name="DEP_CODE", nullable=false, length=1)
    public char getDepCode() {
        return this.depCode;
    }
    
    public void setDepCode(char depCode) {
        this.depCode = depCode;
    }

    
    @Column(name="RSR_ID", nullable=false)
    public int getRsrId() {
        return this.rsrId;
    }
    
    public void setRsrId(int rsrId) {
        this.rsrId = rsrId;
    }




}


