package com.daisyit.entity;
// Generated Mar 4, 2018 1:44:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catering generated by hbm2java
 */
@Entity
@Table(name="CATERING"
    ,catalog="NSRP_CATER"
)
public class Catering  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CateringId id;
     private String mealType;
     private String zoneSymb;
     private byte shift;
     private byte meal;
     private byte catered;
     private String caterTime;
     private byte status;
     private short wsId;
     private short userId;
     private Date openDate;
     private Date modiDate;

    public Catering() {
    }

	
    public Catering(CateringId id, String mealType, String zoneSymb, byte shift, byte meal, byte catered, String caterTime, byte status, short wsId, short userId) {
        this.id = id;
        this.mealType = mealType;
        this.zoneSymb = zoneSymb;
        this.shift = shift;
        this.meal = meal;
        this.catered = catered;
        this.caterTime = caterTime;
        this.status = status;
        this.wsId = wsId;
        this.userId = userId;
    }
    public Catering(CateringId id, String mealType, String zoneSymb, byte shift, byte meal, byte catered, String caterTime, byte status, short wsId, short userId, Date openDate, Date modiDate) {
       this.id = id;
       this.mealType = mealType;
       this.zoneSymb = zoneSymb;
       this.shift = shift;
       this.meal = meal;
       this.catered = catered;
       this.caterTime = caterTime;
       this.status = status;
       this.wsId = wsId;
       this.userId = userId;
       this.openDate = openDate;
       this.modiDate = modiDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="staffId", column=@Column(name="STAFF_ID", nullable=false, length=12) ), 
        @AttributeOverride(name="mealTtme", column=@Column(name="MEAL_TTME", nullable=false, length=1) ), 
        @AttributeOverride(name="caterDate", column=@Column(name="CATER_DATE", nullable=false, length=19) ) } )
    public CateringId getId() {
        return this.id;
    }
    
    public void setId(CateringId id) {
        this.id = id;
    }

    
    @Column(name="MEAL_TYPE", nullable=false, length=2)
    public String getMealType() {
        return this.mealType;
    }
    
    public void setMealType(String mealType) {
        this.mealType = mealType;
    }

    
    @Column(name="ZONE_SYMB", nullable=false, length=4)
    public String getZoneSymb() {
        return this.zoneSymb;
    }
    
    public void setZoneSymb(String zoneSymb) {
        this.zoneSymb = zoneSymb;
    }

    
    @Column(name="SHIFT", nullable=false, precision=2, scale=0)
    public byte getShift() {
        return this.shift;
    }
    
    public void setShift(byte shift) {
        this.shift = shift;
    }

    
    @Column(name="MEAL", nullable=false)
    public byte getMeal() {
        return this.meal;
    }
    
    public void setMeal(byte meal) {
        this.meal = meal;
    }

    
    @Column(name="CATERED", nullable=false)
    public byte getCatered() {
        return this.catered;
    }
    
    public void setCatered(byte catered) {
        this.catered = catered;
    }

    
    @Column(name="CATER_TIME", nullable=false, length=5)
    public String getCaterTime() {
        return this.caterTime;
    }
    
    public void setCaterTime(String caterTime) {
        this.caterTime = caterTime;
    }

    
    @Column(name="STATUS", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="WS_ID", nullable=false, precision=3, scale=0)
    public short getWsId() {
        return this.wsId;
    }
    
    public void setWsId(short wsId) {
        this.wsId = wsId;
    }

    
    @Column(name="USER_ID", nullable=false, precision=3, scale=0)
    public short getUserId() {
        return this.userId;
    }
    
    public void setUserId(short userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OPEN_DATE", length=19)
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODI_DATE", length=19)
    public Date getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(Date modiDate) {
        this.modiDate = modiDate;
    }




}


