package com.daisyit.entity;
// Generated Mar 7, 2018 1:04:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Deptlist generated by hbm2java
 */
@Entity
@Table(name="DEPTLIST"
    ,catalog="NSRP_CATER"
)
public class Deptlist  implements java.io.Serializable {


     private String deptId;
     private String deptName;

    public Deptlist() {
    }

    public Deptlist(String deptId, String deptName) {
       this.deptId = deptId;
       this.deptName = deptName;
    }
   
     @Id 

    
    @Column(name="DEPT_ID", unique=true, nullable=false, length=4)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    
    @Column(name="DEPT_NAME", nullable=false, length=120)
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }




}


