package com.daisyit.entity;
// Generated Mar 4, 2018 1:44:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,catalog="NSRP_CATER"
)
public class Users  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
     private String nodeId;
     private int type;
     private String name;
     private String fullname;
     private long password;
     private String passcode;
     private String staffId;
     private Date lastDate;
     private int rgtLevel;
     private String groups;
     private String SEqual;
     private String RMenus;
     private String confirms;
     private String stations;
     private String trans;
     private String reports;
     private String MDepts;
     private String MFns;
     private String smtphost;
     private short smtpport;
     private short smtpssl;
     private String smtpemail;
     private String smtpuser;
     private String smtppw;
     private byte login;
     private byte status;
     private byte chk;
     private String langType;
     private String stock;

    public Users() {
    }

	
    public Users(int id, String nodeId, int type, String name, String fullname, long password, String passcode, String staffId, int rgtLevel, String groups, String SEqual, String RMenus, String confirms, String stations, String trans, String reports, String MDepts, String MFns, String smtphost, short smtpport, short smtpssl, String smtpemail, String smtpuser, String smtppw, byte login, byte status, byte chk, String langType, String stock) {
        this.id = id;
        this.nodeId = nodeId;
        this.type = type;
        this.name = name;
        this.fullname = fullname;
        this.password = password;
        this.passcode = passcode;
        this.staffId = staffId;
        this.rgtLevel = rgtLevel;
        this.groups = groups;
        this.SEqual = SEqual;
        this.RMenus = RMenus;
        this.confirms = confirms;
        this.stations = stations;
        this.trans = trans;
        this.reports = reports;
        this.MDepts = MDepts;
        this.MFns = MFns;
        this.smtphost = smtphost;
        this.smtpport = smtpport;
        this.smtpssl = smtpssl;
        this.smtpemail = smtpemail;
        this.smtpuser = smtpuser;
        this.smtppw = smtppw;
        this.login = login;
        this.status = status;
        this.chk = chk;
        this.langType = langType;
        this.stock = stock;
    }
    public Users(int id, String nodeId, int type, String name, String fullname, long password, String passcode, String staffId, Date lastDate, int rgtLevel, String groups, String SEqual, String RMenus, String confirms, String stations, String trans, String reports, String MDepts, String MFns, String smtphost, short smtpport, short smtpssl, String smtpemail, String smtpuser, String smtppw, byte login, byte status, byte chk, String langType, String stock) {
       this.id = id;
       this.nodeId = nodeId;
       this.type = type;
       this.name = name;
       this.fullname = fullname;
       this.password = password;
       this.passcode = passcode;
       this.staffId = staffId;
       this.lastDate = lastDate;
       this.rgtLevel = rgtLevel;
       this.groups = groups;
       this.SEqual = SEqual;
       this.RMenus = RMenus;
       this.confirms = confirms;
       this.stations = stations;
       this.trans = trans;
       this.reports = reports;
       this.MDepts = MDepts;
       this.MFns = MFns;
       this.smtphost = smtphost;
       this.smtpport = smtpport;
       this.smtpssl = smtpssl;
       this.smtpemail = smtpemail;
       this.smtpuser = smtpuser;
       this.smtppw = smtppw;
       this.login = login;
       this.status = status;
       this.chk = chk;
       this.langType = langType;
       this.stock = stock;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NODE_ID", nullable=false, length=3)
    public String getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    
    @Column(name="TYPE", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="FULLNAME", nullable=false, length=60)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="PASSWORD", nullable=false, precision=18, scale=0)
    public long getPassword() {
        return this.password;
    }
    
    public void setPassword(long password) {
        this.password = password;
    }

    
    @Column(name="PASSCODE", nullable=false, length=16)
    public String getPasscode() {
        return this.passcode;
    }
    
    public void setPasscode(String passcode) {
        this.passcode = passcode;
    }

    
    @Column(name="STAFF_ID", nullable=false, length=12)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_DATE", length=19)
    public Date getLastDate() {
        return this.lastDate;
    }
    
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }

    
    @Column(name="RGT_LEVEL", nullable=false)
    public int getRgtLevel() {
        return this.rgtLevel;
    }
    
    public void setRgtLevel(int rgtLevel) {
        this.rgtLevel = rgtLevel;
    }

    
    @Column(name="GROUPS", nullable=false, length=128)
    public String getGroups() {
        return this.groups;
    }
    
    public void setGroups(String groups) {
        this.groups = groups;
    }

    
    @Column(name="S_EQUAL", nullable=false, length=128)
    public String getSEqual() {
        return this.SEqual;
    }
    
    public void setSEqual(String SEqual) {
        this.SEqual = SEqual;
    }

    
    @Column(name="R_MENUS", nullable=false, length=128)
    public String getRMenus() {
        return this.RMenus;
    }
    
    public void setRMenus(String RMenus) {
        this.RMenus = RMenus;
    }

    
    @Column(name="CONFIRMS", nullable=false, length=128)
    public String getConfirms() {
        return this.confirms;
    }
    
    public void setConfirms(String confirms) {
        this.confirms = confirms;
    }

    
    @Column(name="STATIONS", nullable=false, length=128)
    public String getStations() {
        return this.stations;
    }
    
    public void setStations(String stations) {
        this.stations = stations;
    }

    
    @Column(name="TRANS", nullable=false, length=128)
    public String getTrans() {
        return this.trans;
    }
    
    public void setTrans(String trans) {
        this.trans = trans;
    }

    
    @Column(name="REPORTS", nullable=false, length=128)
    public String getReports() {
        return this.reports;
    }
    
    public void setReports(String reports) {
        this.reports = reports;
    }

    
    @Column(name="M_DEPTS", nullable=false, length=128)
    public String getMDepts() {
        return this.MDepts;
    }
    
    public void setMDepts(String MDepts) {
        this.MDepts = MDepts;
    }

    
    @Column(name="M_FNS", nullable=false, length=128)
    public String getMFns() {
        return this.MFns;
    }
    
    public void setMFns(String MFns) {
        this.MFns = MFns;
    }

    
    @Column(name="SMTPHOST", nullable=false, length=50)
    public String getSmtphost() {
        return this.smtphost;
    }
    
    public void setSmtphost(String smtphost) {
        this.smtphost = smtphost;
    }

    
    @Column(name="SMTPPORT", nullable=false, precision=3, scale=0)
    public short getSmtpport() {
        return this.smtpport;
    }
    
    public void setSmtpport(short smtpport) {
        this.smtpport = smtpport;
    }

    
    @Column(name="SMTPSSL", nullable=false, precision=3, scale=0)
    public short getSmtpssl() {
        return this.smtpssl;
    }
    
    public void setSmtpssl(short smtpssl) {
        this.smtpssl = smtpssl;
    }

    
    @Column(name="SMTPEMAIL", nullable=false, length=50)
    public String getSmtpemail() {
        return this.smtpemail;
    }
    
    public void setSmtpemail(String smtpemail) {
        this.smtpemail = smtpemail;
    }

    
    @Column(name="SMTPUSER", nullable=false, length=50)
    public String getSmtpuser() {
        return this.smtpuser;
    }
    
    public void setSmtpuser(String smtpuser) {
        this.smtpuser = smtpuser;
    }

    
    @Column(name="SMTPPW", nullable=false, length=50)
    public String getSmtppw() {
        return this.smtppw;
    }
    
    public void setSmtppw(String smtppw) {
        this.smtppw = smtppw;
    }

    
    @Column(name="LOGIN", nullable=false)
    public byte getLogin() {
        return this.login;
    }
    
    public void setLogin(byte login) {
        this.login = login;
    }

    
    @Column(name="STATUS", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="CHK", nullable=false)
    public byte getChk() {
        return this.chk;
    }
    
    public void setChk(byte chk) {
        this.chk = chk;
    }

    
    @Column(name="LANG_TYPE", nullable=false, length=2)
    public String getLangType() {
        return this.langType;
    }
    
    public void setLangType(String langType) {
        this.langType = langType;
    }

    
    @Column(name="STOCK", nullable=false, length=128)
    public String getStock() {
        return this.stock;
    }
    
    public void setStock(String stock) {
        this.stock = stock;
    }




}


