package com.daisyit.entity;
// Generated Mar 7, 2018 6:20:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AllcodeId generated by hbm2java
 */
@Embeddable
public class AllcodeId  implements java.io.Serializable {


     private String codeName;
     private char depCode;
     private String codeVal;

    public AllcodeId() {
    }

    public AllcodeId(String codeName, char depCode, String codeVal) {
       this.codeName = codeName;
       this.depCode = depCode;
       this.codeVal = codeVal;
    }
   


    @Column(name="CODE_NAME", nullable=false, length=10)
    public String getCodeName() {
        return this.codeName;
    }
    
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }


    @Column(name="DEP_CODE", nullable=false, length=1)
    public char getDepCode() {
        return this.depCode;
    }
    
    public void setDepCode(char depCode) {
        this.depCode = depCode;
    }


    @Column(name="CODE_VAL", nullable=false, length=2)
    public String getCodeVal() {
        return this.codeVal;
    }
    
    public void setCodeVal(String codeVal) {
        this.codeVal = codeVal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AllcodeId) ) return false;
		 AllcodeId castOther = ( AllcodeId ) other; 
         
		 return ( (this.getCodeName()==castOther.getCodeName()) || ( this.getCodeName()!=null && castOther.getCodeName()!=null && this.getCodeName().equals(castOther.getCodeName()) ) )
 && (this.getDepCode()==castOther.getDepCode())
 && ( (this.getCodeVal()==castOther.getCodeVal()) || ( this.getCodeVal()!=null && castOther.getCodeVal()!=null && this.getCodeVal().equals(castOther.getCodeVal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeName() == null ? 0 : this.getCodeName().hashCode() );
         result = 37 * result + this.getDepCode();
         result = 37 * result + ( getCodeVal() == null ? 0 : this.getCodeVal().hashCode() );
         return result;
   }   


}


