package com.daisyit.entity;
// Generated Mar 7, 2018 6:20:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catering generated by hbm2java
 */
@Entity
@Table(name="CATERING"
    ,catalog="NSRP_CATER"
)
public class Catering  implements java.io.Serializable {


     private CateringId id;
     private String mealId;
     private String zoneSymb;
     private String shift;
     private boolean catered;
     private String caterTime;
     private boolean status;
     private String wsId;
     private String userId;
     private Date openDate;
     private Date modiDate;

    public Catering() {
    }

	
    public Catering(CateringId id, String mealId, boolean catered, String caterTime, boolean status) {
        this.id = id;
        this.mealId = mealId;
        this.catered = catered;
        this.caterTime = caterTime;
        this.status = status;
    }
    public Catering(CateringId id, String mealId, String zoneSymb, String shift, boolean catered, String caterTime, boolean status, String wsId, String userId, Date openDate, Date modiDate) {
       this.id = id;
       this.mealId = mealId;
       this.zoneSymb = zoneSymb;
       this.shift = shift;
       this.catered = catered;
       this.caterTime = caterTime;
       this.status = status;
       this.wsId = wsId;
       this.userId = userId;
       this.openDate = openDate;
       this.modiDate = modiDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="staffId", column=@Column(name="STAFF_ID", nullable=false, length=12) ), 
        @AttributeOverride(name="mealTtme", column=@Column(name="MEAL_TTME", nullable=false, length=2) ), 
        @AttributeOverride(name="caterDate", column=@Column(name="CATER_DATE", nullable=false, length=10) ) } )
    public CateringId getId() {
        return this.id;
    }
    
    public void setId(CateringId id) {
        this.id = id;
    }

    
    @Column(name="MEAL_ID", nullable=false, length=2)
    public String getMealId() {
        return this.mealId;
    }
    
    public void setMealId(String mealId) {
        this.mealId = mealId;
    }

    
    @Column(name="ZONE_SYMB", length=4)
    public String getZoneSymb() {
        return this.zoneSymb;
    }
    
    public void setZoneSymb(String zoneSymb) {
        this.zoneSymb = zoneSymb;
    }

    
    @Column(name="SHIFT", length=2)
    public String getShift() {
        return this.shift;
    }
    
    public void setShift(String shift) {
        this.shift = shift;
    }

    
    @Column(name="CATERED", nullable=false)
    public boolean isCatered() {
        return this.catered;
    }
    
    public void setCatered(boolean catered) {
        this.catered = catered;
    }

    
    @Column(name="CATER_TIME", nullable=false, length=5)
    public String getCaterTime() {
        return this.caterTime;
    }
    
    public void setCaterTime(String caterTime) {
        this.caterTime = caterTime;
    }

    
    @Column(name="STATUS", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="WS_ID", length=3)
    public String getWsId() {
        return this.wsId;
    }
    
    public void setWsId(String wsId) {
        this.wsId = wsId;
    }

    
    @Column(name="USER_ID", length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="OPEN_DATE", length=10)
    public Date getOpenDate() {
        return this.openDate;
    }
    
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODI_DATE", length=19)
    public Date getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(Date modiDate) {
        this.modiDate = modiDate;
    }




}


