package com.daisyit.entity;
// Generated Mar 7, 2018 6:20:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Meal generated by hbm2java
 */
@Entity
@Table(name="MEAL"
    ,catalog="NSRP_CATER"
)
public class Meal  implements java.io.Serializable {


     private Integer mealId;
     private String mealName;
     private String origin;
     private String description;

    public Meal() {
    }

    public Meal(String mealName, String origin, String description) {
       this.mealName = mealName;
       this.origin = origin;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MEAL_ID", unique=true, nullable=false)
    public Integer getMealId() {
        return this.mealId;
    }
    
    public void setMealId(Integer mealId) {
        this.mealId = mealId;
    }

    
    @Column(name="MEAL_NAME", nullable=false, length=30)
    public String getMealName() {
        return this.mealName;
    }
    
    public void setMealName(String mealName) {
        this.mealName = mealName;
    }

    
    @Column(name="ORIGIN", nullable=false, length=50)
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


