package com.daisyit.entity;
// Generated Mar 7, 2018 1:04:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name="STAFF"
    ,catalog="NSRP_CATER"
)
public class Staff  implements java.io.Serializable {


     private String staffId;
     private String staffCode;
     private String name;
     private String title;
     private String address;
     private String address2;
     private String country;
     private String phone;
     private String fax;
     private String email;
     private String skype;
     private String facebook;
     private String bankAcc;
     private String bank;
     private String deptId;
     private char sex;
     private Date birthday;
     private Integer userId;
     private String cardId;
     private String zoneSymb;
     private String mealType;
     private boolean status;

    public Staff() {
    }

	
    public Staff(String staffId, String name, String deptId, char sex, String cardId, boolean status) {
        this.staffId = staffId;
        this.name = name;
        this.deptId = deptId;
        this.sex = sex;
        this.cardId = cardId;
        this.status = status;
    }
    public Staff(String staffId, String staffCode, String name, String title, String address, String address2, String country, String phone, String fax, String email, String skype, String facebook, String bankAcc, String bank, String deptId, char sex, Date birthday, Integer userId, String cardId, String zoneSymb, String mealType, boolean status) {
       this.staffId = staffId;
       this.staffCode = staffCode;
       this.name = name;
       this.title = title;
       this.address = address;
       this.address2 = address2;
       this.country = country;
       this.phone = phone;
       this.fax = fax;
       this.email = email;
       this.skype = skype;
       this.facebook = facebook;
       this.bankAcc = bankAcc;
       this.bank = bank;
       this.deptId = deptId;
       this.sex = sex;
       this.birthday = birthday;
       this.userId = userId;
       this.cardId = cardId;
       this.zoneSymb = zoneSymb;
       this.mealType = mealType;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="STAFF_ID", unique=true, nullable=false, length=12)
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    
    @Column(name="STAFF_CODE", length=20)
    public String getStaffCode() {
        return this.staffCode;
    }
    
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="TITLE", length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="ADDRESS", length=120)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="ADDRESS2", length=120)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="COUNTRY", length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="PHONE", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="FAX", length=24)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="SKYPE", length=60)
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }

    
    @Column(name="FACEBOOK", length=60)
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }

    
    @Column(name="BANK_ACC", length=50)
    public String getBankAcc() {
        return this.bankAcc;
    }
    
    public void setBankAcc(String bankAcc) {
        this.bankAcc = bankAcc;
    }

    
    @Column(name="BANK", length=120)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }

    
    @Column(name="DEPT_ID", nullable=false, length=4)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    
    @Column(name="SEX", nullable=false, length=1)
    public char getSex() {
        return this.sex;
    }
    
    public void setSex(char sex) {
        this.sex = sex;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BIRTHDAY", length=19)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="USER_ID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="CARD_ID", nullable=false, length=12)
    public String getCardId() {
        return this.cardId;
    }
    
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    
    @Column(name="ZONE_SYMB", length=4)
    public String getZoneSymb() {
        return this.zoneSymb;
    }
    
    public void setZoneSymb(String zoneSymb) {
        this.zoneSymb = zoneSymb;
    }

    
    @Column(name="MEAL_TYPE", length=2)
    public String getMealType() {
        return this.mealType;
    }
    
    public void setMealType(String mealType) {
        this.mealType = mealType;
    }

    
    @Column(name="STATUS", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


