package com.daisyit.entity;
// Generated Mar 7, 2018 6:20:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sysvar generated by hbm2java
 */
@Entity
@Table(name="SYSVAR"
    ,catalog="NSRP_CATER"
)
public class Sysvar  implements java.io.Serializable {


     private String name;
     private Character type;
     private String value;
     private String descript;
     private String inputmask;
     private Boolean modify;
     private String invalid;
     private Character depCode;
     private Integer rsrId;

    public Sysvar() {
    }

	
    public Sysvar(String name, String value) {
        this.name = name;
        this.value = value;
    }
    public Sysvar(String name, Character type, String value, String descript, String inputmask, Boolean modify, String invalid, Character depCode, Integer rsrId) {
       this.name = name;
       this.type = type;
       this.value = value;
       this.descript = descript;
       this.inputmask = inputmask;
       this.modify = modify;
       this.invalid = invalid;
       this.depCode = depCode;
       this.rsrId = rsrId;
    }
   
     @Id 

    
    @Column(name="NAME", unique=true, nullable=false, length=15)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="TYPE", length=1)
    public Character getType() {
        return this.type;
    }
    
    public void setType(Character type) {
        this.type = type;
    }

    
    @Column(name="VALUE", nullable=false, length=120)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="DESCRIPT", length=120)
    public String getDescript() {
        return this.descript;
    }
    
    public void setDescript(String descript) {
        this.descript = descript;
    }

    
    @Column(name="INPUTMASK", length=12)
    public String getInputmask() {
        return this.inputmask;
    }
    
    public void setInputmask(String inputmask) {
        this.inputmask = inputmask;
    }

    
    @Column(name="MODIFY")
    public Boolean getModify() {
        return this.modify;
    }
    
    public void setModify(Boolean modify) {
        this.modify = modify;
    }

    
    @Column(name="INVALID", length=12)
    public String getInvalid() {
        return this.invalid;
    }
    
    public void setInvalid(String invalid) {
        this.invalid = invalid;
    }

    
    @Column(name="DEP_CODE", length=1)
    public Character getDepCode() {
        return this.depCode;
    }
    
    public void setDepCode(Character depCode) {
        this.depCode = depCode;
    }

    
    @Column(name="RSR_ID")
    public Integer getRsrId() {
        return this.rsrId;
    }
    
    public void setRsrId(Integer rsrId) {
        this.rsrId = rsrId;
    }




}


